### ISSUE TITLE
Markierung folgt nur der Maus und nicht dem Cursor

### ISSUE THREAD

**Issue by BrunoKaiser** [cybi/jluatree#3]
Die Markierung über den Button "Markieren" richtet sich nach dem zuletzt mit der Maus ausgewählten Ast bzw. Knoten. Wenn man mit dem Cursor woanders hingeht, wird nicht der neue Ast bzw. Knoten markiert.

**Comment by PlutonicJ** [comment]
@BrunoKaiser Bitte einmal testen.

**Comment by BrunoKaiser** [comment]
Der Test ist erfolgreich. Die Markierung folgt jetzt auch dem Cursor.
